create table if not exists scan_results (
  id bigint generated by default as identity primary key,
  account_email text not null,
  message_id text not null,
  verdict text not null,
  stats jsonb,
  url_results jsonb,
  file_results jsonb,
  created_at timestamptz not null default now()
);

create index if not exists scan_results_account_message_idx
  on scan_results (account_email, message_id, created_at desc);

create unique index if not exists scan_results_unique_msg
  on scan_results (account_email, message_id);

create table if not exists scan_url_cache (
  url text primary key,
  verdict text not null,
  stats jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists scan_file_cache (
  sha256 text primary key,
  filename text,
  verdict text not null,
  stats jsonb,
  updated_at timestamptz not null default now()
);
